FROM golang:1.16.3 AS build
WORKDIR /workdir
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o bin/client ./cmd/client

FROM scratch
COPY --from=build /workdir/bin/client /client
ENTRYPOINT [ "/client" ]
